sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: o8rpgg2PzHlJhcvZWKb1kewodt+wf2YECG5n3vJpwCymEuMWAAP2as6yGiAu4vg+es/ZcDw64H+j7J86NfADaKsfj4y0nIsGSp1/yMr5ER8L/BCxqQuMTmJjlSCrFxYeUCarHW+sB2WQ3FIheYnpgS8iKsFl6NG+pBLfS85ru+pwd0FEEFRegbrj0L3IKmLX9vpzmRVM4wghXOXHUxq0JoEcgNPl4Ia03jOvIyo87Qv50nabttncFSHM0mNWgG3xsaicTjgzAimHcBNCxDDV0BHKPWqbRygT6uORQZYOgeVMockjzZ28taIAtl54PRz9vIV+hWQGLVFeL9jZKW89D2FmHOjJ8rKWcv/Cpsnlew26kLd7OM3iefHzKemU942+nNPzJ1E0R0wT591wQFdGcbN+fT1Mp0UJ+WwGpY6g+YSWccimTnQODMW6CQxLmwT06o0vCIf397rFqWmwL9nY9XGj+vu2mXkIN9eeZA+Boq6JZmDhO09shpJXjCvCzB3oqHO1r/SYjdNfNGDYUtBbnadW5XMC7MqUSeT4LruaEWymFrtlgA5UvQzp/GHLr4wG2Yun6x/mVQglzZw6yl5CCLAg+Jvk2ffEr1HC0gyhZEUDfzf3IzFACW7YKJKJXmS7uUREHeSv3wf64OdKsN32Uu0wLUkYjfYY05oycjO63EQ=

branches:
  only:
    - /^v\d.*$/
    - master
    - develop

php:
  - 5.6
  - 7.1

env:
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=0

matrix:
  fast_finish: true
  exclude:
    - php: 7.1
      env: WP_VERSION=4.4 WP_MULTISITE=0

install:
  - export DEV_LIB_PATH=bin/dev-lib
  - export DEV_LIB_SKIP=codeception,jscs,jshint,yuicompressor,phpunit,xmllint
  - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
  - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
  - source $DEV_LIB_PATH/travis.install.sh

script:
  - source $DEV_LIB_PATH/travis.script.sh

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh

before_deploy:
  - npm install
  # Build the plugin for deployment
  - grunt 'Build the plugin.'

deploy:
  provider: releases
  api_key:
    secure: RSvHNlAizdIyV6MI9QtYCREHN7ByGEPZUB/Wp0Ex13uSxNprM9PHOMaV8NrJ5b9uLGo4lje4VWVX73BoufFhi83/1oXi0pcNzwJ+5NEscrfwdkNXpDJnWr9tCOVcJXykM7b8vg1+etJIjxTvB5TyBm5z6ZxFP1/Mmsl0UHnHuWuAUEYHd5n1MmitCIkFR60imfd4FsTHPn4nxK2tlCY4jkz78ovyKXfSB8lHinIdvagYjAbIpHbTEb4RGwoYlUCL7htODJrVnQpXQuHe0YGD7rdKhV4ebQS/pUX2z05LSntezw0CvbMjS20uZjg+frdsMSl8d+TLcLFNaRJJdxcabfRGmtHOzwAH6e00H0BufrsVr+4+OI3N7DDYP8z/7GKzwuEyrarxvxzu+jgwU/6m5zFGLH443lOjC6rpgXsjjx8pKrjTNhGWr353aXcrdg1C6aZbbsgHlca7CAubvpL6P5raISL8/9jvg3CDbTpkLUdN7ht5ml4bKyC2XRpn6JsV8ADa2O92pu3s3PjDVhETkAVZtBBpWbsXG9U8qf6cf+hq8boWFzcV00zkFMumc+6FpwGfnwdz6RTBJzw5HK8DbLZ4J8G7+8ngQ+j1qsIrewTW3qMEquIsevz3IsIXhr4IuP5IPxkKgKv6OesurTCiWJteflcQbBuRwzwkJ8EFBUg=
  file_glob: true
  file: build/timeline-express-no-icons-add-on-*.zip
  on:
    tags: true
    repo: CodeParrots/timeline-express-no-icons-add-on
    php: '7.1'
    condition: "$WP_VERSION=trunk"
  skip_cleanup: true
  overwrite: true
